vich_uploader:
    db_driver: orm

    mappings:
        page_image:
            uri_prefix: /images/page
            upload_destination: '%kernel.project_dir%/public/images/page'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer


